### ISSUE TITLE
ORA-04043: object SDO_ELEM_INFO_ARRAY does not exist on Oracle 11.2.0.4

### ISSUE THREAD

**Issue by mattpoel** [oracle/python-cx_Oracle#9] opened 2017-03-30 23:41 UTC
Describe exactly what you did and what you want to happen:

**First of all, thanks a lot for your hard work and for bringing the feature to build & write SDO_GEOMETRY objects!**

I've upgrade my cx_Oracle version to 5.3 in order to be able to build / write SDO_GEOMETRY data (without SQL or PL/SQL) and I am currently testing my code with the following matching Oracle versions (in order not to run into an `OCI-22351`):

* Oracle Instant Client 11.2.0.4 => Oracle Database 11.2.0.4
* Oracle Instant Client 12.1.0.2 => Oracle Database 12.1.0.2

I used the sample code from `InsertGeometry.py` for writing some sample data:

```
...
typeObj = connection.gettype("SDO_GEOMETRY")
elementInfoTypeObj = connection.gettype("SDO_ELEM_INFO_ARRAY")
ordinateTypeObj = connection.gettype("SDO_ORDINATE_ARRAY")
...
```

This works fine for 12.1.0.2, but on 11.2.0.4, I'm receiving the following error:

```
elementInfoTypeObj = connection.gettype("SDO_ELEM_INFO_ARRAY")
cx_Oracle.DatabaseError: ORA-04043: object SDO_ELEM_INFO_ARRAY does not exist
```

In order to fix it, I had to add the MDSYS schemata:

```
typeObj = connection.gettype("MDSYS.SDO_GEOMETRY")
elementInfoTypeObj = connection.gettype("MDSYS.SDO_ELEM_INFO_ARRAY")
ordinateTypeObj = connection.gettype("MDSYS.SDO_ORDINATE_ARRAY")
```

Not sure if this is actually an issue by cx_Oracle or just related to my 11.2.0.4 database, but I wanted to report the behavior. If this issue also encountered during your tests, the example maybe could be extended to use the fully qualified type to be compatible with all Oracle Database versions.

Thanks in advance!

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?

`Python 3.5.1 / 64-Bit`

2. What is your version of cx_Oracle?

`5.3`

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?

```
Oracle Instant Client 11.2.0.4 / Linux 64-Bit
/opt/oracle-ic_11.2.0.4

&

Oracle Instant Client 12.1.0.2 / Linux 64-Bit
/opt/oracle-ic_12.1.0.2
```

cx_Oracle has been installed in two different environments to be linked against the according version.

4. What is your OS and version?

`Oracle Linux Server release 7.1 / 64-Bit`

5. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.

`gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)`

6. What environment variables did you set?  How *exactly* did you set them?

```
export ORACLE_HOME=/opt/oracle-ic_11.2.0.4
export LD_LIBRARY_PATH=$ORACLE_HOME
```

**Comment by anthony-tuininga** [comment] 2017-03-31 02:25
I just confirmed this behaviour on my own 11.2.0.4 database so it isn't just yours! The differences may be due to the availability of a more advanced OCI function in 12c but I'll confirm. And I'll also adjust the samples accordingly based on what answers I get. Thanks for letting me know about this.

**Comment by anthony-tuininga** [comment] 2017-03-31 14:36
In discussion with some spatial experts including the schema MDSYS is the right way to go to work around limitations in Oracle 11g. I have just committed changes to the sample that do just that. Thanks again for letting me know.

**Closed by anthony-tuininga** 2017-03-31 14:36 UTC
