### ISSUE TITLE
Wont build on windows

### ISSUE THREAD

**Issue by roda37** [oracle/python-cx_Oracle#668] opened 2024-04-10 07:15 UTC
![Untitled](https://github.com/oracle/python-cx_Oracle/assets/55464245/39a173f9-170a-4b56-9d6f-4b562e4bf893)

I keep getting this message, I am not very good with windows but I am pretty sure I've installed the build tools and every known C++ package both x86 and 64 and it still wont build the package, any help?

**Comment by cjbj** [comment] 2024-04-10 09:05
The common root cause is trying to use cx_Oracle with versions of Python that were released after cx_Oracle 8.3 itself was release. I.e. Pre-built cx_Oracle binaries packages are not available for those Python versions.   The best solution in this case is to upgrade cx_Oracle so the new version's pre-built binary packages install directly without you needing to compile.  See the original [release announcement](https://cjones-oracle.medium.com/open-source-python-thin-driver-for-oracle-database-e82aac7ecf5a) for the upgrade.

**Comment by roda37** [comment] 2024-04-10 10:23
> The common root cause is trying to use cx_Oracle with versions of Python that were released after cx_Oracle 8.3 itself was release. I.e. Pre-built cx_Oracle binaries packages are not available for those Python versions. The best solution in this case is to upgrade cx_Oracle so the new version's pre-built binary packages install directly without you needing to compile. See the original [release announcement](https://cjones-oracle.medium.com/open-source-python-thin-driver-for-oracle-database-e82aac7ecf5a) for the upgrade.


The main reason why I use this client instead of the new oracledb client is because the new one does not support old databases, when you run the script with this new library you will always get this:

`DPY-3010: connections to this database server version are not supported by python-oracledb in thin mode`

The old one (cx_Oracle) works with Oracle Database 11g that I have deployed here, which cannot be upgraded or changed. Hey I'm just trying to do my job :). Could you perhaps point me to the prebuilt packages, or could it be built with mingw?

On Linux cx_Oracle works really nice, yes it's annoying to have a client installed but as long as it works it's fine. On Windows however it will fail no matter what. I don't know anything about packaging on pip, perhaps someone here does so it can be fixed.

**Comment by cjbj** [comment] 2024-04-10 13:06
The new driver, python-oracledb, **works fine Oracle DB 11gR2**: you just need to add a call to [`init_oracle_client()`](https://python-oracledb.readthedocs.io/en/latest/user_guide/initialization.html#enabling-python-oracledb-thick-mode) in your scripts so the Oracle Client libraries are linked, just like they always were with cx_Oracle.  The Thick mode is now optional in python-oracledb, but was the only choice with cx_Oracle.

**Comment by cjbj** [comment] 2024-04-23 01:40
Closing - no update

**Closed by cjbj** 2024-04-23 01:40 UTC
Labels: install & configuration
