### ISSUE TITLE
Please reopen issue #540. It is reproduced in cx_Oracle 8.2

### ISSUE THREAD

**Issue by NisSAM** [oracle/python-cx_Oracle#573] opened 2021-06-30 09:44 UTC
1. What versions are you using?

2. Is it an error or a hang or a crash?

3. What error(s) or behavior you are seeing?

4. Include a runnable Python script that shows the problem.

**Comment by cjbj** [comment] 2021-06-30 09:57
Let's use this (573) issue, since the other is concluded.

Please update this issue with version information, and give us the SQL to create the table & data, and the code that shows the problem.

Also review https://cx-oracle.readthedocs.io/en/latest/user_guide/sql_execution.html#fetching-raw-data and https://cx-oracle.readthedocs.io/en/latest/user_guide/sql_execution.html#querying-corrupt-data

**Comment by QZBASF** [comment] 2021-07-05 16:00
Continuation of #540 
1. platform.platform: Linux-5.3.18-24.64-default-x86_64-with-glibc2.3.4
sys.maxsize > 2**32: True
platform.python_version: 3.6.13
cx_Oracle.version: 8.2.1 

2. Is it an error or a hang or a crash?
Crash

**Is this an environment where the table is being recreated frequently?** 
No.
For reproducing issue case, we are doing this way. It was detected good in integration testing.  
If I run the same module again, issue will not be there.

So recommended to drop and create the tables.

**Have you tried disabling the statement cache?**
After your suggestion, I have disabled statement cache to 0.
But it is not helping.

**Do you have corrupt data - or a flaky network?** 
If data is corrupted, then next run also it should fail. But in the next run data is processed successfully, after stopping and starting the batch job. 
Network is good.  But I can't confirm.

**Have you tried a recent Oracle Client, e.g. 19.11**
Yes After your suggestion, I have tried with the oracle 19.11 
With the oracle 19.11 version, select query data with execute gives incorrect data elements structure issue seems to be reduced, but not 100%. Now instead of this data structure error, UTF-8 error is raised

**Example: incorrect data element**
**with Oracle Client 12.2** - only error starting places i have shown. other data elements please refer above comment.

'Q_USER', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 11, 11, None, None, 1
'Q_USER\x00\x00T_GRUP', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 4, 4, None, None, 1

**with Oracle Client 19.11**

'Q_USER', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 11, 11, None, None, 1
'XVUA_CDIX_KOMM', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 4, 4, None, None, 1


**Short Code just reference**
Error raised during cursor.description
```
def select(self, command, parms=None):
    self.rowcount = 0
    self.execute_cursor(command, parms)
    cursor = self.cursor
    print(cursor.description)
    
def execute_cursor(self, command, parms=None):
    cursor = self.cursor
    try:
        if parms is None:
            cursor.execute(command)
        elif type(parms) is str:
            cursor.execute(command, {"1": parms})
        elif type(parms) is dict:
            cursor.execute(command, parms)
```

Note:
1) Sometimes Because of this, some of the data is missing for corresponding column_name during select query with out UnicoideDecodeError UTF 8 Error also.

2) When UnicoideDecodeError : UTF8 error raising,  and above point 1 issue.
With the same module, I can stop the batch job and start again will give success for same code and same data. Which is magic.

Kindly help on this. It is very urgent.
As of now, we have implemented workaround as whenever UTF 8 error raises. Stoping the job and starting again automatically.


> * @QZBASF please open a new issue, since it's not clear you have the same problem.  Be clear about the order of statements.  I got lost with what you were doing.
> * Is this an environment where the table is being recreated frequently?  Have you tried disabling the statement cache?
> * Do you have corrupt data - or a flaky network? https://cx-oracle.readthedocs.io/en/latest/user_guide/sql_execution.html#fetching-raw-data
> * Have you tried a recent Oracle Client, e.g. 19.11

**Comment by QZBASF** [comment] 2021-08-09 08:20
Hello cx_Oracle Team,

Please provide the update on the issues..

**Comment by cjbj** [comment] 2021-08-09 09:35
See previous update.

Did you review https://cx-oracle.readthedocs.io/en/latest/user_guide/sql_execution.html#fetching-raw-data and https://cx-oracle.readthedocs.io/en/latest/user_guide/sql_execution.html#querying-corrupt-data ?

What steps from them did you follow?

 > Please update this issue with version information, and give us the SQL to create the table & data, and the code that shows the problem.

We need a reproducible test case that requires only to change the connection credentials.

**Comment by cjbj** [comment] 2022-03-06 23:53
Closing - requested info not available.

**Closed by cjbj** 2022-03-06 23:53 UTC
Labels: bug
