### ISSUE TITLE
Oracle.ProgrammingError: positional and named binds cannot be intermixed (==6.4)

### ISSUE THREAD

**Issue by jakereps** [oracle/python-cx_Oracle#199] opened 2018-07-03 16:48 UTC
Discovered in unit testing due to no version pinning in the project's Pipfile. Locally (`6.3.1`) remains functional, while all database set up tasks fail in our CI pipeline on `cx_Oracle==6.4`.

Binding errors stating that positional and named binds cannot be intermixed when there are no positional binds being used.

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?

```bash
$ python -V
Python 3.6.5
$ python -c 'import sys; print(sys.maxsize)'
9223372036854775807  # 64bit
```

2. What is your version of cx_Oracle?

Locally:

```bash
$ python -c 'import cx_Oracle; print(cx_Oracle.__version__)'
6.3.1
```

Remote (issue causing)

```bash
$ python -c 'import cx_Oracle; print(cx_Oracle.__version__)'
6.4
```

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?

```bash
$ ls /opt/oracle/
instantclient_12_2
```

4. What is your version of the Oracle Database?

```bash
$ docker ps
CONTAINER ID        IMAGE                                            COMMAND                  CREATED             STATUS                    PORTS                                 NAMES
ffe765d011a3        store/oracle/database-enterprise:12.2.0.1-slim   "/bin/sh -c '/bin/ba…"   29 minutes ago      Up 29 minutes (healthy)   5500/tcp, 127.0.0.1:XXXXX->1521/tcp   inspiring_shtern
```
5. What is your OS and version?

```bash
$ uname -a
Darwin Jordens-MacBook-Pro.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.13.5 (17F77)
      Kernel Version: Darwin 17.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Jorden’s MacBook Pro
      User Name: Jorden Kreps (jordenkreps)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 6 days 1:57
```

6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.

```bash
$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

7. What environment variables did you set?  How *exactly* did you set them?

N/A

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?

```bash
$ pytest --cov <package_name>
```

9. What error(s) you are seeing?

#### 6.3.1

```bash
...
<package_name>/tests/test_util.py ...............                            [100%]
...
```

#### 6.4
```bash
...
<package_name>/tests/test_util.py EEEEEE.........                            [100%]
...

self = <sqlalchemy.dialects.oracle.cx_oracle.OracleDialect_cx_oracle object at 0x7f977ca76550>
cursor = <cx_Oracle.Cursor on <cx_Oracle.Connection to SYSTEM@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=XXXXX))(CONNECT_DATA=(SID=ORCLCDB)(SERVICE_NAME=ORCLPDB1.localdomain)))>>
statement = 'SELECT table_name FROM all_tables WHERE table_name = :name AND owner = :schema_name'
parameters = {'name': 'MYTABLE', 'schema_name': 'MYUSER'}
context = <sqlalchemy.dialects.oracle.cx_oracle.OracleExecutionContext_cx_oracle object at 0x7f977cb570b8>

    def do_execute(self, cursor, statement, parameters, context=None):
>       cursor.execute(statement, parameters)
E       cx_Oracle.ProgrammingError: positional and named binds cannot be intermixed
```

Pinning to 6.3.1 resolves the issue.

**Comment by anthony-tuininga** [comment] 2018-07-03 16:58
Can you provide a test case that fails? Or provide instructions on getting the unit tests you are referencing up and running so I can see what is going on? Thanks!

**Comment by jakereps** [comment] 2018-07-03 17:40
For sure, it happens in the `setUp` portion of the `unittest.TestCase`, where we are making and destroying tables before and after every test so the data remains at the initial state for each test. Since the tests are erring out at the set up stage, the test code itself isn't even being ran. 

Here is essentially our `setUp` code that recreates the error on `cx_Oracle==6.4`, but works as expected on `==6.3.1`.

```python 
import sqlalchemy
import cx_Oracle
from sqlalchemy import Table, Column, MetaData, String

user = "SYSTEM"
password = "Oradoc_db1"

dsn = cx_Oracle.makedsn("127.0.0.1", <DOCKER_ASSIGNED_PORT>, "ORCLCDB", 
                        service_name="ORCLPDB1.localdomain")
connection_str = f"oracle+cx_oracle://{user}:{password}@{dsn}"
engine = sqlalchemy.create_engine(connection_str)

md = MetaData(bind=engine)

schema_name = "sone"
table_name = "table1"

engine.execute(f"CREATE USER {schema_name} IDENTIFIED BY test")
engine.execute(f"ALTER USER {schema_name} QUOTA UNLIMITED ON USERS")

columns = []
for column in ('foo', 'bar', 'baz'):
    columns.append(Column(column.upper(), String(50), nullable=True, 
                          quote=False))

_ = Table(table_name, md, *columns, schema=schema_name, quote=False, 
          quote_schema=False)

md.create_all()
```

**Comment by anthony-tuininga** [comment] 2018-07-03 19:24
Thanks for the test case. That was sufficient to track this issue down. Essentially a bug fix in cx_Oracle 6.4 inadvertently introduced this issue. Calling cursor.setinputsizes() with no parameters at all would make the assumption that you were binding by position, so a subsequent call to cursor.execute() with named arguments would immediately raise this issue. Although it makes no sense to call cursor.setinputsizes() with no parameters, it also shouldn't cause any problems! I'll get this corrected.

**Comment by anthony-tuininga** [comment] 2018-07-03 19:37
I have corrected this issue and added a test case that should prevent this issue from happening in the future. I'll wait a while before releasing cx_Oracle 6.4.1, just to ensure there aren't any other issues. Thanks again for reporting this issue.

**Comment by jakereps** [comment] 2018-07-03 20:21
Awesome, thanks! No problem on holding out a hot fix, as we’ll just keep an eye out and unpin the version at that time!

**Comment by Peque** [comment] 2018-07-04 10:21
Maybe it would make sense to leave this open until 6.4.1 is out. This way users wanting to report this issue (like me) only need to check if it is already reported in the "open" issues list (easier to see in my opinion).

**Comment by anthony-tuininga** [comment] 2018-07-04 15:41
Re-opening as requested. Will close again once 6.4.1 has been released.

**Comment by zzzeek** [comment] 2018-07-05 03:29
yep...i'm getting this too :)    can you refer to the patch, and/or did you add tests for this?

**Comment by zzzeek** [comment] 2018-07-05 03:31
oh sorry i see it above

**Comment by vinayinfo** [comment] 2018-07-06 08:19
I am getting the Same error. to fix that I have downgraded to v6.3.1

**Comment by pgacv2** [comment] 2018-07-06 16:40
Confirmed, downgrading to 6.3.1 avoids that error.

**Comment by mkai** [comment] 2018-07-09 11:41
I have the same problem – I think it affects everyone using SQLAlchemy. Waiting to upgrade until 6.4.1 is released.

**Comment by anthony-tuininga** [comment] 2018-07-09 19:51
cx_Oracle 6.4.1 has been released with this issue corrected in it.

**Closed by anthony-tuininga** 2018-07-09 19:51 UTC
Labels: bug

**Comment by felixxm** [comment] 2018-07-11 12:31
Many thanks Anthony :rocket:

**Comment by anthony-tuininga** [comment] 2018-08-16 21:16
Not sure what you are asking exactly. The issue on which you are commenting was corrected in cx_Oracle 6.4.1. If you have a new issue, please open a new issue and carefully explain what you are asking. Thanks.

**Comment by mPyth** [comment] 2018-08-17 06:17
Ok, thx for prompt answer.

**Comment by hmkaraca** [comment] 2018-12-26 16:54
We have the same with version cx_oracle 7.0 which we didn' t have with version 6.4. Can you please check and advice?

**Comment by cjbj** [comment] 2018-12-27 06:32
@hmkaraca please give a (runnable) python script and sql to create any data.  Thanks.

**Comment by hmkaraca** [comment] 2018-12-27 10:39
Please find document attached. Code works with version 6.2.1 properly, whereas it fails with above error with 7.0. Thanks.
[docs.zip](https://github.com/oracle/python-cx_Oracle/files/2712210/docs.zip)

**Comment by hmkaraca** [comment] 2018-12-30 12:43
Is there any update on this?

**Comment by hmkaraca** [comment] 2018-12-31 09:53
[code.zip](https://github.com/oracle/python-cx_Oracle/files/2718154/code.zip)
Please find code attached. I tried to minimize and modified sql, like below.
args={}
args['EXECUTIONGUID']='B3B6A70F330CA04CA1609D7AC8FD1FC0'
sql="""SELECT \'EXECUTIONGUID\' FROM DUAL"""

**Comment by hmkaraca** [comment] 2019-01-06 16:51
Is this information enough to check?

**Comment by hmkaraca** [comment] 2019-01-07 07:16
Sorry, I converted it to a single file as attached. You can run just as python test_db_con.py. Thanks.
[test_db_con.zip](https://github.com/oracle/python-cx_Oracle/files/2731733/test_db_con.zip)

**Comment by anthony-tuininga** [comment] 2019-01-07 18:35
Ok. That does indeed replicate the issue. The problem is that you are calling cursor.setinputsizes() with an empty dictionary and the code looks for the presence of at least one keyword argument before considering the method to be "bind by name". So the code is assuming that you are binding by position since you didn't actually provide any keyword arguments. There isn't much point in calling setinputsizes() in this case...although I will grant you that the error message is a bit confusing!

As an aside, you aren't actually using bind variables at all but simply doing a search/replace. What you should have instead is something like this:

```python
cursor.execute("select :execution_guid from dual",
        execution_guid="B3B6A70F330CA04CA1609D7AC8FD1FC0")
```

That's far simpler! You should only use setinputsizes() if you need to deviate from the default bind types.

**Comment by hmkaraca** [comment] 2019-01-07 19:13
Actually, this was the simplest case to reproduce the problem, however, even if I use setinputsizes without empty dictionary, we have the same problem, that' s why I submitted this. I don' t have the problem with same code using version cx_oracle 6.2.1

**Comment by BrajeshBhadoriya** [comment] 2019-01-07 20:38
I am reading an excel sheet and trying to load it into Oracle. 
Below is the code:
file = pd.read_excel('data.xlsx')
finaldf = file.reindex(sorted(file.columns), axis=1)
finaldata = [tuple(x) for x in finaldf.astype(str).values]
cols = ','.join(map(str,list(finaldf.columns)))
s = ":"
wildcards = ""
for i in range(1, len(finaldf.columns) + 1):
    wildcards += "".join(["replace(", s, str(i), ",'\\n',CHR(10))", ","])
wildcards = wildcards[:-1]
stmt = ''.join(['INSERT INTO ', 'TABLE' , '(', cols, ') VALUES', '(', wildcards, ')'])
conn_str='Setting Connection'
conn = Cx_oracle.connect(conn_str)
cur = conn.cursor()
cur.setinputsizes(ora.LONG_STRING)
cur.executemany(stmt, finaldata)
conn.commit()
conn.close()

But this is failing with cx_Oracle.DatabaseError: ORA-01461: can bind a LONG value only for insert into a LONG column error. I know that there are two columns which has size of 3990. If I remove those two columns, data load is going normal. Can someone please help.

I have also tried with positional column names but it was giving "Oracle.ProgrammingError: positional and named binds cannot be intermixed" error. Please help.

Thank you
Brajesh.

**Comment by cjbj** [comment] 2019-01-07 20:47
@BrajeshBhadoriya please delete your comment and open new issue because it not related to the topic.

**Comment by anthony-tuininga** [comment] 2019-01-08 21:42
I corrected the issue with calling cursor.setinputsizes() with an empty dict. If you are having problems in other situations, please provide a new test case -- and open a new issue! Thanks.
