### ISSUE TITLE
Can't call a stored function with a ref cursor as a IN parameter

### ISSUE THREAD

**Issue by foo-bar-py** [oracle/python-cx_Oracle#355] opened 2019-09-05 15:56 UTC
Hello,

I successfully call stored procedures, witch returns ref cursors, with cx_Oracle.
But I have an issue trying to call a function, passing a ref cursor as a "in parameter".

I try to use a function defined in a package like this (it has a ref cursor as a in parameter, and it returns another ref cursor as a result):

FUNCTION put_cmd(in_ref_cur_cmd IN in_ref_cur_type) RETURN out_ref_cur_cmd;

Here is my python code:
```python
import cx_Oracle
connection = cx_Oracle.connect('user/pass@localhost/mysid')

# multiline cursor needs to be send to the function
in_ref_cur_cmd = connection.cursor()
in_ref_cur_cmd.execute( "select 'foo' from dual union select 'bar' from dual")

cursor = connection.cursor()
result = cursor.callfunc('my_pck.put_cmd', cx_Oracle.CURSOR, (in_ref_cur_cmd))
# fails and throws a "ORA-01002: fetch out of sequence" error.
```

Python Version: 3.6.8
cx_Oracle Version: 6.1
oracleinstantclient Version: 12.2
Oracle server Version : 11g R2

**Comment by anthony-tuininga** [comment] 2019-09-06 04:07
I can confirm this is due to prefetch. If the query fetches only one row it has already been prefetched and the cursor is aware that there are no more rows -- so you get the "fetch out of sequence" error. If the query fetches two rows, both will already have been prefetched but you won't get any errors. If the query fetches more than two rows you'll get the third row (and any subsequent ones). There is a way to disable the prefetch but this is not enabled with cx_Oracle today. I'll mark this as an enhancement, but for now you'll have to retrieve two dummy rows so that you can get at the real rows in the PL/SQL function!

**Comment by cjbj** [comment] 2019-09-06 04:51
This is related to https://github.com/oracle/odpi/issues/73

**Comment by foo-bar-py** [comment] 2019-09-10 15:46
It solved my problem.
Thanks !

**Comment by cjbj** [comment] 2019-09-10 16:50
Let's leave this open as a reminder that some cx_Oracle changes are needed, or tests need to be added.

**Comment by anthony-tuininga** [comment] 2020-06-12 22:03
I've added some code that enables this capability now. Here is some sample code:

```python
cursor = conn.cursor()

ref_cursor = conn.cursor()
ref_cursor.prefetchrows = 0
ref_cursor.execute("""
        select 1, 'String 1' from dual
        union all
        select 2, 'String 2' from dual
        union all
        select 3, 'String 3' from dual
        union all
        select 4, 'String 4' from dual
        union all
        select 5, 'String 5' from dual""")
cursor.callproc("some_proc", (ref_cursor,))
```

**Comment by anthony-tuininga** [comment] 2020-06-26 17:27
cx_Oracle 8 was just released with these changes.

**Closed by anthony-tuininga** 2020-06-26 17:27 UTC
Labels: Patch Available, enhancement
