### ISSUE TITLE
cursror.description throws UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 4: invalid start byte

### ISSUE THREAD

**Issue by NisSAM** [oracle/python-cx_Oracle#540] opened 2021-02-18 10:05 UTC
1. What versions are you using?

19.8.0.0.0
platform.platform: Windows-10-10.0.17134-SP0
sys.maxsize > 2**32: True
platform.python_version: 3.9.0
cx_Oracle.version: 8.1.0
cx_Oracle.clientversion: (19, 3, 0, 0, 0)

2. Is it an error or a hang or a crash?
error
3. What error(s) or behavior you are seeing?

It is fails at the 2nd `print(curs1.description)` with errors like this `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 4: invalid start byte`

4. Include a runnable Python script that shows the problem.

It is **not** a full script because it is very difficult to make a real test case. I can reproduce problem at home at will, but if I change set of columns (remove or add) in the **select** it may disappear or appear in unpredictable way. But the behavior will be the same for every run of constant sql text.
```
        connection = cxo.Connection(user='scott', password='tiger, dsn='orac', threaded=True,  encoding='utf-8', nencoding='utf-8')
        curs1.parse('select some CLOB and other columns from table')
        print(curs1.description)
        curs1.execute(None, dict(some_binds))
        print(curs1.description)
```

**Comment by cjbj** [comment] 2021-02-18 10:42
Can you post a full NLS environment (DB side, any locale settings in the OS, etc.)?
As you can guess, without a test case there's little that can be done by us.

Do you need to fetch LOBs with locators or can you fetch as strings? https://github.com/oracle/python-cx_Oracle/blob/master/samples/ReturnLobsAsStrings.py

It always helps to upgrade so we all use the same set of binaries when testing.  Instant Client 19.10 is available for Windows.

**Comment by NisSAM** [comment] 2021-02-18 11:17
I have installed cx_Oracle.clientversion: (19, 10, 0, 0, 0). Nothing changed. It is floating bug. I tried using 
```
def LobTypeHandler(cursor, name, defaultType, size, precision, scale):
    if defaultType == cxo.DB_TYPE_CLOB:
        return cursor.var(cxo.DB_TYPE_LONG, arraysize=cursor.arraysize)
    if defaultType == cxo.DB_TYPE_BLOB:
        return cursor.var(cxo.DB_TYPE_LONG_RAW, arraysize=cursor.arraysize)
connection.outputtypehandler = LobTypeHandler
```
But in this case the error will be thrown at execute call. I've already tried to change NLS setting and remove it at all. Nothing changes. I do understand that good test case will help, but it is very difficult to create. I will try.

I can try to collect some diagnostics if you tell me how to collect.

**Comment by NisSAM** [comment] 2021-02-18 11:56
It looks like I've managed to reproduce it as relatively simple test case. It looks stupid but if I change anything the error will disappear.
```
create table cx_oracle_test4(SQL_TEXT CLOB, DBID number not null, CON_DBID number not null, SQL_ID VARCHAR2(13) not null);
insert into cx_oracle_test4 values('Test', 1763210951, 1763210951, 'fz8fg3fqa5ph4');
commit;
```
```
import platform
import sys

import cx_Oracle as cxo

print("platform.platform:", platform.platform())
print("sys.maxsize > 2**32:", sys.maxsize > 2 ** 32)
print("platform.python_version:", platform.python_version())

print("cx_Oracle.version:", cxo.version)
print("cx_Oracle.clientversion:", cxo.clientversion())


def LobTypeHandler(cursor, name, defaultType, size, precision, scale):
    if defaultType == cxo.DB_TYPE_CLOB:
        return cursor.var(cxo.DB_TYPE_LONG, arraysize=cursor.arraysize)
    if defaultType == cxo.DB_TYPE_BLOB:
        return cursor.var(cxo.DB_TYPE_LONG_RAW, arraysize=cursor.arraysize)


sql_text = """
    select sql_text, length(sql_text)  as "Length", 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10
      from cx_oracle_test4
     where sql_id       = :sql_id
       and dbid = :dbid and con_dbid = :con_dbid and :xxx = :xxx
"""

if __name__ == '__main__':
    connection = cxo.Connection(user='scott', password='tiger', dsn='orac', encoding='utf-8', nencoding='utf-8')
    # connection.outputtypehandler = LobTypeHandler
    curs1 = connection.cursor()
    curs1.parse(sql_text)
    print(curs1.description)
    curs1.execute(None, dict(xxx='15868959584152974442', sql_id='fz8fg3fqa5ph4', dbid=1763210951, con_dbid=1763210951))
    print(curs1.description)

    for r in curs1:
        print(r)
```

**Comment by anthony-tuininga** [comment] 2021-02-18 16:19
I just tried this on Linux and didn't get any errors. Trying on a Windows platform will take more effort as I don't use Windows daily. I'll see if someone else can try this on Windows that uses it more regularly. Can you also post the database version and platform you are using?

**Comment by NisSAM** [comment] 2021-02-18 20:11
Anthony, try to make some small changes. Add or remove some columns etc. Error can appear if you add or remove column and disappear if you add or remove another one. But the **same query** will always run without any error or always run with error. So the bug randomly depends on shape of the query but is reproduced at every run.

I run client on 64 bit Windows 10 and 19.8 database is run on Linux. Tomorrow I will try to reproduce the error on Linux client.

**Comment by NisSAM** [comment] 2021-02-19 14:42
I couldn't reproduce the error on Linux with Python 3.6.8. At the moment there some are problems with Python 3.9 installation on the host where I can run test case.
```
platform.platform: Linux-3.10.0-1160.2.2.el7.x86_64-x86_64-with-oracle-7.9
sys.maxsize > 2**32: True
platform.python_version: 3.6.8
cx_Oracle.version: 8.1.0
cx_Oracle.clientversion: (19, 10, 0, 0, 0)
```

**Comment by suniljoy** [comment] 2021-02-19 21:41
I am able to reproduce this on Windows.
Not sure if it is something to do with encoding. I saw this error when I used encoding and nencoding equal to UTF-8. When I used UTF-16, I didn't see the error.

python version: 3.7.7
cx_Oracle.version : 8.1.0
client version : 19.9.0.0.0
server version: 19.11.0.0.0

**Comment by NisSAM** [comment] 2021-03-16 06:33
What can we do to speedup resolution?

**Comment by cjbj** [comment] 2021-03-16 06:49
For the record, I don't see a problem on macOS with 19.8 client.

**Comment by suniljoy** [comment] 2021-05-19 14:36
Just tried something similar to the test case given above. Instead of 10 as a number, I have tried fetching it as a char in select query and I kept increasing the no. of fetches. At certain number, it gave NULL.. probably that's where its throwing error. Looks like After certain number of fetches, is it failing to allocate memory by any chance..

Here is what I have tried..  the sql statement.. See the no. of '10's there..
`sql_text = """
    select sql_text, length(sql_text)  as "Length", '10', '10', '10', '10', '10', '10'
      from cx_oracle_test4
     where sql_id       = :sql_id
       and dbid = :dbid and con_dbid = :con_dbid and :xxx = :xxx
"""`

Output1:

`python.exe issue540.py
platform.platform: Windows-10-10.0.14393-SP0
sys.maxsize > 2**32: True
platform.python_version: 3.8.6
cx_Oracle.version: 8.0.1
cx_Oracle.clientversion: (19, 9, 0, 0, 0)
('SQL_TEXT', <cx_Oracle.DbType DB_TYPE_CLOB>, None, None, None, None, 1)
('Length', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, None, None, 1)
("'10'", <cx_Oracle.DbType DB_TYPE_CHAR>, 2, 8, None, None, 1)
("'10'", <cx_Oracle.DbType DB_TYPE_CHAR>, 2, 8, None, None, 1)
("'10'", <cx_Oracle.DbType DB_TYPE_CHAR>, 2, 8, None, None, 1)
("'10'", <cx_Oracle.DbType DB_TYPE_CHAR>, 2, 8, None, None, 1)
("'10'", <cx_Oracle.DbType DB_TYPE_CHAR>, 2, 8, None, None, 1)
("'10'", <cx_Oracle.DbType DB_TYPE_CHAR>, 2, 8, None, None, 1)
("'10'", <cx_Oracle.DbType DB_TYPE_CHAR>, 2, 8, None, None, 1)`


Next case: Just added another '10'
` select sql_text, length(sql_text)  as "Length", '10', '10', '10', '10', '10', '10', '10'
      from cx_oracle_test4
     where sql_id       = :sql_id
       and dbid = :dbid and con_dbid = :con_dbid and :xxx = :xxx`

Output2:

`python.exe issue540.py
platform.platform: Windows-10-10.0.14393-SP0
sys.maxsize > 2**32: True
platform.python_version: 3.8.6
cx_Oracle.version: 8.0.1
cx_Oracle.clientversion: (19, 9, 0, 0, 0)
('Length\x00\x00', <cx_Oracle.DbType DB_TYPE_CLOB>, None, None, None, None, 1)
("'10'\x00\x00", <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, None, None, 1)
('\x00\x00\x00\x00', <cx_Oracle.DbType DB_TYPE_CHAR>, 2, 8, None, None, 1)
('\x00\x00\x00\x00', <cx_Oracle.DbType DB_TYPE_CHAR>, 2, 8, None, None, 1)
('\x00\x00\x00\x00', <cx_Oracle.DbType DB_TYPE_CHAR>, 2, 8, None, None, 1)
('\x00\x00\x00\x00', <cx_Oracle.DbType DB_TYPE_CHAR>, 2, 8, None, None, 1)
('\x00\x00\x00\x00', <cx_Oracle.DbType DB_TYPE_CHAR>, 2, 8, None, None, 1)
('\x00\x00\x00\x00', <cx_Oracle.DbType DB_TYPE_CHAR>, 2, 8, None, None, 1)
('\x00\x00\x00\x00', <cx_Oracle.DbType DB_TYPE_CHAR>, 2, 8, None, None, 1)
('\x19\x00\x00\x00', <cx_Oracle.DbType DB_TYPE_CHAR>, 2, 8, None, None, 1)
`

@anthony-tuininga Didn't see this happening with cx_Oracle-8.2.

**Comment by anthony-tuininga** [comment] 2021-05-19 15:11
@NisSAM, can you try with cx_Oracle 8.2 (just released) and let us know if the issue still reproduces for you?

**Comment by cjbj** [comment] 2021-05-19 23:27
> can you try with cx_Oracle 8.2 (just released) and let us know if the issue still reproduces for you?

See the last line of the comment https://github.com/oracle/python-cx_Oracle/issues/540#issuecomment-844167369:

> Didn't see this happening with cx_Oracle-8.2.

So we should be able to close this issue?

For future readers with related errors, also see https://cx-oracle.readthedocs.io/en/latest/user_guide/sql_execution.html#fetching-raw-data and https://cx-oracle.readthedocs.io/en/latest/user_guide/sql_execution.html#querying-corrupt-data

**Comment by QZBASF** [comment] 2021-06-10 06:26
Hello All,

We need a solution or advise for this bug.
Bug still exists in latest Oracle version  8.2.1 released on Jun 1st 2021 also. 

cx-Oracle         8.2.1
Python 3.6.13 (default, Mar 10 2021, 18:30:35) [GCC] on linux (SLES 15.2)
instantclient_12_2
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit

Issue case can be reproducable first time only. If you run the module again then it will be success. 
So need to drop the table, before inserting entry into the table.
Then recreate table again via module and insert few entries.
next execute cursor with update statement (any update).
next execute cursor for 1st select statement with parms :1 should be q_user (username)
 ```
select *
    from qztuser
    where fr_name in (
        select fr_name
        from qztuser
        where upper(q_user) = upper(:1)
         or upper(fr_name) = upper(:1)
        )
```

next execute the cursor for 2nd select statement here parms :1 should be fr_name (email - string length more than 35).

based on fr_name field length we can identify two difference issue.

Type 1: if field length 2000 BYTE. Then incorrect structure will start again in middle with Q_USER\x00\x00T_GRUP. please look inside..

`[('Q_USER', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 11, 11, None, None, 1), ('T_GRUPPE', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 2, 2, None, None, 1), ('T_CODE', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 10, 10, None, None, 1), ('LAND', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 3, 3, None, None, 1), ('ADM_DOM', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 96, 96, None, None, 1), ('PRIV_DOM', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 96, 96, None, None, 1), ('NACHNAME', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 240, 240, None, None, 1), ('VORNAME', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 240, 240, None, None, 1), ('INITIALE', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 10, 10, None, None, 1), ('ORG_EINHEIT', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 32, 32, None, None, 1), ('FR_NAME', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 82, 328, None, None, 1), ('TELEFON', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 30, 30, None, None, 1), ('D_NODE', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 10, 10, None, None, 1), ('D_USER', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 10, 10, None, None, 1), ('ABTCODE', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 20, 80, None, None, 1), ('ABT_BAU', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 50, 50, None, None, 1), ('AUFNAHME_DAT', <cx_Oracle.DbType DB_TYPE_DATE>, 23, None, None, None, 1), ('DIALOG', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 1, 1, None, None, 1), ('ANZAHL', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('TKS_FAXNR', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 30, 30, None, None, 1), ('Q_USER\x00\x00T_GRUP', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 4, 4, None, None, 1), ('T_CODE\x00\x00LAND\x00\x00\x00\x00', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('ADM_DOM\x00PRIV', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('NACHNAMEVORN', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('INITIALEORG_', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('EIT\x00\x00\x00\x00\x00FR_NAME', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('TELEFON\x00D_NODE\x00\x00', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('D_USER\x00\x00ABTCOD', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('ABT_BAU\x00AUFNAH', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('_DAT\x00\x00\x00\x00DIALOG\x00', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('ANZAHL\x00\x00TKS_FAX', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('R\x00\x00\x00\x00\x00\x00\x00XVUA_CDI', <cx_Oracle.DbType DB_TYPE_DATE>, 23, None, None, None, 1), ('X_KOMM\x00\x00', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 8, 8, None, None, 1), ('MAX_WZ_MAHN', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 8, 8, None, None, 1), ('ANZ_EMPF_MS', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 2, 2, None, None, 1), ('ANZ_SEN', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 10, 10, None, None, 1), ('_MSG\x00\x00\x00\x00', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 4, 4, None, None, 1), ('ANZ_FEHL_', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 20, 20, None, None, 1), ('ANZ_MAIL_Z', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 30, 30, None, None, 1), ('ANZ_FAX_PER_MAIL', <cx_Oracle.DbType DB_TYPE_DATE>, 23, None, None, None, 1), ('ANZ_FAX_ZERTIS\x00', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 10, 10, None, None, 1), ('ANZ_FAX_BELEGT\x00\x00', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 120, 120, None, None, 1), ('ANZ_FAX_POSITI', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 4, 4, None, None, 1), ('ANZ_FAX_NEGAT', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 16, 16, None, None, 1), ('SET_ANZ_N', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 1000, 1000, None, None, 1), ('IMS_SB', <cx_Oracle.DbType DB_TYPE_DATE>, 23, None, None, None, 1), ('IMS_DRUCKER\x00\x00\x00\x00\x00', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 4, 4, None, None, 1), ('IMS_ZUGRIFF\x00', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 8, 8, None, None, 1), ('QS_CODE\x00QS_B', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 8, 8, None, None, 1), ('QS_SBNAME\x00\x00\x00\x00\x00\x00\x00Q', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 4, 4, None, None, 1), ('ON\x00\x00\x00\x00\x00\x00AENDE', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 8, 8, None, None, 1), ('GS_ZEITPAENDE', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 8, 8, None, None, 1), ('GS_USER\x00AENDERUN', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 4, 4, None, None, 1), ('GS_GRUNDGCD_', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 8, 8, None, None, 1), ('ANY_ID\x00\x00GCD_', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 8, 8, None, None, 1), ('CT_ID\x00\x00\x00BEMERKUNG', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 4, 4, None, None, 1), ('LZUDAT\x00\x00XE_OR', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 8, 8, None, None, 1), ('COMP_KEYXE_OR', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 8, 8, None, None, 1), ('APPL\x00\x00\x00\x00X', <cx_Oracle.DbType DB_TYPE_CHAR>, 1, 1, None, None, 1), ('INST\x00\x00\x00', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 40, 40, None, None, 1), ('XE_RECIP_COM', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 10, 10, None, None, 1), ('Y\x00\x00\x00\x00\x00\x00\x00', <cx_Oracle.DbType DB_TYPE_DATE>, 23, None, None, None, 1)]`

Type 2: if field length 100 BYTE
```
  File "/www/qz/qz/oracle/qzform00.py", line 1774, in geheimzahl_vergessen
    A.select(s_qztuserdaten, d["Kennung"])
  File "/www/qz/qz/qzoralib.py", line 273, in select
    c = cursor.description
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xee in position 0: invalid continuation byte
```

Correct Structure of cursor.execute:
`[('Q_USER', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 11, 11, None, None, 1), ('T_GRUPPE', <cR>, 2, 2, None, None, 1), ('T_CODE', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 10, 10, None, DbType DB_TYPE_VARCHAR>, 3, 3, None, None, 1), ('ADM_DOM', <cx_Oracle.DbType DB_TYPE_VA, ('PRIV_DOM', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 96, 96, None, None, 1), ('NACHNAME',CHAR>, 240, 240, None, None, 1), ('VORNAME', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 240, 2', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 10, 10, None, None, 1), ('ORG_EINHEIT', <cx_Orac, 32, None, None, 1), ('FR_NAME', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 82, 328, None, No.DbType DB_TYPE_VARCHAR>, 30, 30, None, None, 1), ('D_NODE', <cx_Oracle.DbType DB_TYPE_1), ('D_USER', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 10, 10, None, None, 1), ('ABTCODE', HAR>, 20, 80, None, None, 1), ('ABT_BAU', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 50, 50, N, <cx_Oracle.DbType DB_TYPE_DATE>, 23, None, None, None, 1), ('DIALOG', <cx_Oracle.DbTye, None, 1), ('ANZAHL', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('TK_TYPE_VARCHAR>, 30, 30, None, None, 1), ('XVUA_CDIX_KOMM', <cx_Oracle.DbType DB_TYPE_VA('MAX_WZ_MAHNUNGEN', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('ANZ_E_TYPE_NUMBER>, 127, None, 0, -127, 1), ('ANZ_SEND_MSG', <cx_Oracle.DbType DB_TYPE_NUMBEANZ_FEHL_MSG', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('ANZ_MAIL_ZEPE_NUMBER>, 127, None, 0, -127, 1), ('ANZ_FAX_PER_MAIL', <cx_Oracle.DbType DB_TYPE_NUMB'ANZ_FAX_ZERTIS', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('ANZ_FAX_TYPE_NUMBER>, 127, None, 0, -127, 1), ('ANZ_FAX_POSITIV', <cx_Oracle.DbType DB_TYPE_NUM('ANZ_FAX_NEGATIV', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('SET_AN DB_TYPE_DATE>, 23, None, None, None, 1), ('IMS_SBNR', <cx_Oracle.DbType DB_TYPE_VARCHAS_DRUCKER', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 8, 8, None, None, 1), ('IMS_ZUGRIFF', <AR>, 2, 2, None, None, 1), ('QS_CODE', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 10, 10, Noneracle.DbType DB_TYPE_VARCHAR>, 4, 4, None, None, 1), ('QS_SBNAME', <cx_Oracle.DbType DBNone, 1), ('QS_TELEFON', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 30, 30, None, None, 1), ('DbType DB_TYPE_DATE>, 23, None, None, None, 1), ('AENDERUNGS_USER', <cx_Oracle.DbType D None, 1), ('AENDERUNGS_GRUND', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 120, 120, None, NonOracle.DbType DB_TYPE_VARCHAR>, 4, 4, None, None, 1), ('GCD_OBJECT_ID', <cx_Oracle.DbTyone, None, 1), ('BEMERKUNG', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 1000, 1000, None, NoneType DB_TYPE_DATE>, 23, None, None, None, 1), ('XE_ORIG_COMP_KEY', <cx_Oracle.DbType DBne, 1), ('XE_ORIG_APPL', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 8, 8, None, None, 1), ('XE DB_TYPE_VARCHAR>, 8, 8, None, None, 1), ('XE_RECIP_COMP_KEY', <cx_Oracle.DbType DB_TYP1), ('XE_RECIP_APPL', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 8, 8, None, None, 1), ('XE_REB_TYPE_VARCHAR>, 8, 8, None, None, 1), ('XA_ORIG_COMP_KEY', <cx_Oracle.DbType DB_TYPE_V ('XA_ORIG_APPL', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 8, 8, None, None, 1), ('XA_ORIG_IE_VARCHAR>, 8, 8, None, None, 1), ('XA_RECIP_COMP_KEY', <cx_Oracle.DbType DB_TYPE_VARCHA_RECIP_APPL', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 8, 8, None, None, 1), ('XA_RECIP_INSVARCHAR>, 8, 8, None, None, 1), ('LDAP_ONLY', <cx_Oracle.DbType DB_TYPE_CHAR>, 1, 1, NoOracle.DbType DB_TYPE_VARCHAR>, 40, 40, None, None, 1), ('WARNINGLEVEL', <cx_Oracle.DbTNone, None, 1), ('DEADLINE', <cx_Oracle.DbType DB_TYPE_DATE>, 23, None, None, None, 1)]`

**Comment by cjbj** [comment] 2021-06-11 12:05
- @QZBASF please open a new issue, since it's not clear you have the same problem.  Be clear about the order of statements.  I got lost with what you were doing.
- Is this an environment where the table is being recreated frequently?  Have you tried disabling the statement cache?
- Do you have corrupt data - or a flaky network? https://cx-oracle.readthedocs.io/en/latest/user_guide/sql_execution.html#fetching-raw-data
- Have you tried a recent Oracle Client, e.g. 19.11

**Comment by cjbj** [comment] 2021-06-11 12:05
I'm closing this issue since the original problem has concluded.

**Closed by cjbj** 2021-06-11 12:05 UTC
Labels: bug

**Comment by NisSAM** [comment] 2021-06-30 09:41
`platform.platform: Windows-10-10.0.17134-SP0
sys.maxsize > 2**32: True
platform.python_version: 3.9.1
cx_Oracle.version: 8.2.1
cx_Oracle.clientversion: (19, 10, 0, 0, 0)
[('SQL_TEXT', <cx_Oracle.DbType DB_TYPE_CLOB>, None, None, None, None, 1), ('Length', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, None, None, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1)]
Traceback (most recent call last):
  File "pyclob.py", line 37, in <module>
    print(curs1.description)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfb in position 4: invalid start byte

Process finished with exit code 1
`

**Comment by QZBASF** [comment] 2021-06-30 11:23
> I'm closing this issue since the original problem has concluded.

Problem is not solved. 

please reopen.

**Comment by QZBASF** [comment] 2021-07-01 22:55
1. platform.platform: Linux-5.3.18-24.64-default-x86_64-with-glibc2.3.4
sys.maxsize > 2**32: True
platform.python_version: 3.6.13
cx_Oracle.version: 8.2.1 

2. Is it an error or a hang or a crash?
Crash

**Is this an environment where the table is being recreated frequently?** 
No.
For reproducing issue case, we are doing this way. It was detected good in integration testing.  
If I run the same module again, issue will not be there.

So recommended to drop and create the tables.

**Have you tried disabling the statement cache?**
After your suggestion, I have disabled statement cache to 0.
But it is not helping.

**Do you have corrupt data - or a flaky network?** 
If data is corrupted, then next run also it should fail. But in the next run data is processed successfully, after stopping and starting the batch job. 
Network is good.  But I can't confirm.

**Have you tried a recent Oracle Client, e.g. 19.11**
Yes After your suggestion, I have tried with the oracle 19.11 
With the oracle 19.11 version, select query data with execute gives incorrect data elements structure issue seems to be reduced, but not 100%. Now instead of this data structure error, UTF-8 error is raised

**Example: incorrect data element**
**with Oracle Client 12.2** - only error starting places i have shown. other data elements please refer above comment.

'Q_USER', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 11, 11, None, None, 1
'Q_USER\x00\x00T_GRUP', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 4, 4, None, None, 1

**with Oracle Client 19.11**

'Q_USER', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 11, 11, None, None, 1
'XVUA_CDIX_KOMM', <cx_Oracle.DbType DB_TYPE_VARCHAR>, 4, 4, None, None, 1


**Short Code just reference**
Error raised during cursor.description
```
def select(self, command, parms=None):
    self.rowcount = 0
    self.execute_cursor(command, parms)
    cursor = self.cursor
    print(cursor.description)
    
def execute_cursor(self, command, parms=None):
    cursor = self.cursor
    try:
        if parms is None:
            cursor.execute(command)
        elif type(parms) is str:
            cursor.execute(command, {"1": parms})
        elif type(parms) is dict:
            cursor.execute(command, parms)
```

Note:
1) Sometimes Because of this, some of the data is missing for corresponding column_name during select query with out UnicoideDecodeError UTF 8 Error also.

2) When UnicoideDecodeError : UTF8 error raising,  and above point 1 issue.
With the same module, I can stop the batch job and start again will give success for same code and same data. Which is magic.

Kindly help on this. It is very urgent.
As of now, we have implemented workaround as whenever UTF 8 error raises. Stoping the job and starting again automatically.


> * @QZBASF please open a new issue, since it's not clear you have the same problem.  Be clear about the order of statements.  I got lost with what you were doing.
> * Is this an environment where the table is being recreated frequently?  Have you tried disabling the statement cache?
> * Do you have corrupt data - or a flaky network? https://cx-oracle.readthedocs.io/en/latest/user_guide/sql_execution.html#fetching-raw-data
> * Have you tried a recent Oracle Client, e.g. 19.11

**Comment by QZBASF** [comment] 2022-05-05 09:51
> What is the Oracle Database version used by you?
Hope you are using Oracle 12 DB version. 

We also used Oracle Release 12.1.0.2.0 - Production Version. Now I upgraded to Production Version 19.14.0.0.0  and issue seems to be fixed. I didn't get this error. May be you can try if possible.

**Comment by QZBASF** [comment] 2022-05-05 09:54
> `platform.platform: Windows-10-10.0.17134-SP0 sys.maxsize > 2**32: True platform.python_version: 3.9.1 cx_Oracle.version: 8.2.1 cx_Oracle.clientversion: (19, 10, 0, 0, 0) [('SQL_TEXT', <cx_Oracle.DbType DB_TYPE_CLOB>, None, None, None, None, 1), ('Length', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, None, None, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1), ('10', <cx_Oracle.DbType DB_TYPE_NUMBER>, 127, None, 0, -127, 1)] Traceback (most recent call last): File "pyclob.py", line 37, in print(curs1.description) UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfb in position 4: invalid start byte
> 
> Process finished with exit code 1 `

What is the Oracle Database version used by you?
Hope you are using Oracle 12 DB version.

We also used Oracle Release 12.1.0.2.0 - Production Version. Now I upgraded to Production Version 19.14.0.0.0 and issue seems to be fixed. I didn't get this error. May be you can try if possible.

**Comment by offblacc** [comment] 2023-09-13 13:44
Just had the same issue, seemed nondeterministic, hard (impossible) to replicate as everyone said. What did fix it however was *not* calling cursor.description multiple times on the same cursor. Moving the cursor creation and its closing to the start and end of a loop instead of having it outside fixed the problem. My assumption is it gets corrupted somehow.. i dunno...
For those still stuck with this - try not to reuse your cursor, that might do the trick.
