### ISSUE TITLE
Can you execute SQL having Oracle Spatial operators?

### ISSUE THREAD

**Issue by cm0001** [oracle/python-cx_Oracle#403] opened 2020-02-19 19:31 UTC
Can you query a spatial-enabled Oracle database table directly using cx_Oracle (i.e. - can you use [oracle spatial operators](https://docs.oracle.com/database/121/SPATL/spatial-operators.htm#SPATL110) in the sql) ?
I would like to do something like this:
```
sql = "select id into :id from spatialtbl s where sdo_nn(s.geometry, :obj, 'sdo_num_res=1', 1) = 'TRUE'"

try:
    # execute the nearest-neighbor sql
    cur.execute(sql, id=id, obj=geometry_obj)
    print(f'The id is {id.getvalue()}')
except cx_Oracle.Error as error:
    print(error)
```
Python 3.7
Oracle 11.2

**Comment by cjbj** [comment] 2020-02-19 21:45
This appears to be a duplicate of https://stackoverflow.com/questions/60302762/are-spatial-queries-possible-using-python-and-cx-oracle/60309578

**Closed** 2020-02-19 23:17 UTC
Labels: question

**Comment by cm0001** [comment] 2020-02-19 23:19
I think my sql statement was invalid. I found a way to get the answer below.

# set up a distance-calculating sql statement
sql = """select id from spatialtbl s where sdo_nn(s.geometry, :ob, 'sdo_num_res=1', 1) = 'TRUE'"""

try:
    # execute the distance sql
    cur.execute(sql, ob=obj)
    id = cur.fetchone()
    print(f'The id is {id}')
except cx_Oracle.Error as error:
    print(error)
