### ISSUE TITLE
cx_Oracle hides NO_DATA_FOUND exception in an INSERT statement with RETURNING clause.

### ISSUE THREAD

**Issue by felixxm** [oracle/python-cx_Oracle#131] opened 2018-01-01 11:59 UTC
`cx_Oracle` hides `NO_DATA_FOUND` exception in an `INSERT` statement with `RETURNING` clause. Please find below example that should raise `NO_DATA_FOUND` exception:
```python
import cx_Oracle
connection = cx_Oracle.connect("user", "password", "TNS")
cursor = connection.cursor()
cursor.execute('''
    CREATE TABLE "ISSUE_TEST" (
        "ID" NUMBER(11) GENERATED BY DEFAULT ON NULL AS IDENTITY,
        "TEST_CHAR" VARCHAR2(10)
    )
''')
cursor.execute('''
    CREATE OR REPLACE TRIGGER "TRG_NO_DATA_FOUND"
    AFTER INSERT ON "ISSUE_TEST"
    FOR EACH ROW
    BEGIN
        RAISE NO_DATA_FOUND;
    END;
''')
v_id = None
cursor.execute('''
    INSERT INTO "ISSUE_TEST"("TEST_CHAR")
    VALUES('XYZ') RETURNING "ISSUE_TEST"."ID" INTO :v_id
''', {'v_id': v_id})
```
Other exceptions e.g. `DUP_VAL_ON_INDEX`, `ZERO_DIVIDE`, `TOO_MANY_ROWS` are raised properly.

* cx_Oracle 5.3, 6.1
* Python 3.5.3 (64-bit)

**Comment by anthony-tuininga** [comment] 2018-01-02 21:24
I can replicate the issue. Thanks. Note that without the DML returning clause the error is raised. With the DML returning clause the code that populates the returning value never actually runs. This suggests that the OCI library is masking the exception. I've seen this sort of behaviour elsewhere as well. I'll ask internally if there is a way to avoid this behaviour.

**Comment by felixxm** [comment] 2018-01-03 08:30
@anthony-tuininga Yes, I noticed that. Sorry, I should mention this in the issue description (see related Django ticket [#28859](https://code.djangoproject.com/ticket/28859)). Thanks for investigating this.

**Comment by anthony-tuininga** [comment] 2018-01-03 17:55
I asked internally and discovered that this is indeed a bug in the OCI library. Bug #27338462 has been raised internally to address this. Unfortunately, there is no workaround. You'll need to avoid raising the exception "ORA-1403: no data found" if you intend to use a DML returning clause. Sorry!

**Comment by cjbj** [comment] 2018-01-09 01:47
I'm going to close this since the issue is not in cx_Oracle code.  Please follow the Oracle bug mentioned to track the status.  Thanks for reporting it.

**Closed by cjbj** 2018-01-09 01:47 UTC
Labels: bug
