### ISSUE TITLE
Cancel a cursor.execute()

### ISSUE THREAD

**Issue by sergiownd** [oracle/python-cx_Oracle#173] opened 2018-04-26 09:09 UTC
Hi, I'm running a query which takes a long time to finish. I want to be able to kill the connection with CTRL+C or kill PID. I've tried to use the connection.cancel() o the terminate process but the query keeps on executing. I've also tried to make the query on a subprocess but even if i kill the process the query is still executed. Is there any way of cancelling it?

Thanks.

**Comment by sergiownd** [comment] 2018-04-26 14:30
Here is the code:

`import cx_Oracle
import sys
import signal

def signal_term_handler(sig, frame):
    connection.cancel()
    sys.exit('end')

ip = 'localhost'
port = 49161
SID = 'xe'
dsn_tns = cx_Oracle.makedsn(ip, port, SID)
connection = cx_Oracle.connect('system', 'oracle', dsn_tns)
cursor = connection.cursor()

signal.signal(signal.SIGTERM, signal_term_handler)
signal.signal(signal.SIGINT, signal_term_handler)
cursor.execute("create table testear as select * from test union select * from test2 union select * from test3 union select * from test2 union select * from test3 union select * from test2 union select * from test3 union select * from test2 union select * from test3 union select * from test2 union select * from test3 union select * from test2 union select * from test3 union select * from test2 union select * from test3 union select * from test2 union select * from test3 union select * from test2 union select * from test3 union select * from test2 union select * from test3 union select * from test2 union select * from test3 union select * from test2 union select * from test3")


return()`

I've also tried stop it with multiprocess:


`ip = 'localhost'
port = 49161
SID = 'xe'
dsn_tns = cx_Oracle.makedsn(ip, port, SID)
connection = cx_Oracle.connect('system', 'oracle', dsn_tns)
cursor = connection.cursor()

def signal_term_handler(signal, frame):
    cursor.close()
    sys.exit('Excution stopped manually.')

def threat_treatment():
	cursor.execute("create table testear as select * from test union select * from test2 union select * from test3 union select * from test2 union select * from test3 union select * from test2 union select * from test3 union select * from test2 union select * from test3 union select * from test2 union select * from test3 union select * from test2 union select * from test3 union select * from test2 union select * from test3 union select * from test2 union select * from test3 union select * from test2 union select * from test3 union select * from test2 union select * from test3 union select * from test2 union select * from test3 union select * from test2 union select * from test3")


t1 = Process(target=threat_treatment)
signal.signal(signal.SIGTERM, signal_term_handler)
signal.signal(signal.SIGINT, signal_term_handler)
t1.start()

return(1)`

I'm using the latest version of oracle, and I'm user docker to prepare the database with oracle-xe-11g.

Thank you for helping

**Comment by cjbj** [comment] 2018-04-26 22:35
I have a feeling this is a duplicate of https://stackoverflow.com/questions/50019989/cancel-interrupt-a-query-execute-on-cx-oracle

**Comment by sergiownd** [comment] 2018-04-27 06:09
Yes, actually It is my post too.

**Comment by sergiownd** [comment] 2018-04-27 06:39
Where should I add the DISABLE_OOB=on (I'm some kind of new to Oracle) Thanks. And about platform I dont know if u mean my machine or what else.

**Comment by cjbj** [comment] 2018-04-27 07:12
This has some applicable info https://oracle.github.io/node-oracledb/doc/api.html#tnsadmin (the network layer is common with cx_Oracle)

Platform == whatever you are running on: operating system, virtual machines etc.

**Comment by sergiownd** [comment] 2018-04-27 12:26
I'm running the code on a Ubuntu Budgie and the data base running on a docker (oracle-xe-11g)

**Comment by anthony-tuininga** [comment] 2018-05-30 20:08
Closing due to lack of activity.

**Closed by anthony-tuininga** 2018-05-30 20:08 UTC
Labels: question

**Comment by vbvasu** [comment] 2024-02-08 06:18
Hi,
Im trying to execute like 15-20 queries using cx_oracle python
Some of the queries may run long sometimes i am searching for a way to stop the query if its still running for more than 30 min i would like to skip this and cancel the execution and gopn executing other queries.
Is there anyway to track the time and cancel the query execution and skip this

**Comment by anthony-tuininga** [comment] 2024-02-08 19:07
Take a look at the attribute [call_timeout](https://python-oracledb.readthedocs.io/en/latest/api_manual/connection.html#Connection.call_timeout). This is for the replacement for cx_Oracle called python-oracledb but the same information applies to cx_Oracle.

**Comment by vbvasu** [comment] 2024-02-09 00:05
I dont think it will help me resolving the issue.

**Comment by anthony-tuininga** [comment] 2024-02-09 01:34
Why do you think that? Open a new issue with details!
