### ISSUE TITLE
SELECT * FROM ... WHERE vchar_column IN (a, b, c) incredibly slow

### ISSUE THREAD

**Issue by Bluehorn** [oracle/python-cx_Oracle#58] opened 2017-07-28 14:21 UTC
Querying rows using an `COLUMN in VALUES` expression is abysmally slow with current cx_Oracle when using SQLAlchemy. This used to be fast, not sure what lead to this deterioration.

Please find an example script attached that illustrates the issue:

[cxora-performance.zip](https://github.com/oracle/python-cx_Oracle/files/1183299/cxora-performance.zip)

Running this I get these results:

```console
$ virtualenv env
New python executable in /home/torsten.landschoff/cxora-performance/env/bin/python2.7
Also creating executable in /home/torsten.landschoff/cxora-performance/env/bin/python
Installing setuptools, pip, wheel...done.
$ . env/bin/activate
(env) $ pip install -r requirements.txt
Collecting sqlalchemy==1.1.12 (from -r requirements.txt (line 1))
Collecting cx_Oracle==6.0rc2 (from -r requirements.txt (line 2))
Installing collected packages: sqlalchemy, cx-Oracle
Successfully installed cx-Oracle-6.0rc2 sqlalchemy-1.1.12

(env) $ python example.py
Dropping old data...
Inserting example data...
Example data prepped.
Gathering statistics...
Retrieving data using IN queries...
Retrieving 1 rows: 0.07661485672 s (13.0522987683 rows/s)
Retrieving 5 rows: 0.351477861404 s (14.2256470437 rows/s)
Retrieving 10 rows: 0.703488111496 s (14.2148812988 rows/s)
Retrieving 25 rows: 1.7293651104 s (14.4561722968 rows/s)
Retrieving 50 rows: 3.49536585808 s (14.304654228 rows/s)
Retrieving 100 rows: 7.02343797684 s (14.2380413025 rows/s)
```

BTW: This is a Intel Core i7-6700K (Skylake), 32 GB RAM with the database on an SSD on an otherwise unloaded system.

Compare this to an old version of cx_Oracle that we are still using to avoid this problem:

```
(env) $ pip install cx_Oracle==5.2
Collecting cx_Oracle==5.2
Installing collected packages: cx-Oracle
  Found existing installation: cx-Oracle 6.0rc2
    Uninstalling cx-Oracle-6.0rc2:
      Successfully uninstalled cx-Oracle-6.0rc2
Successfully installed cx-Oracle-5.2
(env) $ python example.py
Example data prepped.
Gathering statistics...
Retrieving data using IN queries...
Retrieving 1 rows: 0.00177216529846 s (564.281447599 rows/s)
Retrieving 5 rows: 0.00231099128723 s (2163.57371299 rows/s)
Retrieving 10 rows: 0.00161194801331 s (6203.67401272 rows/s)
Retrieving 25 rows: 0.00187611579895 s (13325.403482 rows/s)
Retrieving 50 rows: 0.00262188911438 s (19070.2191507 rows/s)
Retrieving 100 rows: 0.00516700744629 s (19353.5622001 rows/s)
```

In the hope that this was introduced in 6.0 I also tried cx_Oracle 5.3 but this version is also affected:

```
(env) $ pip install cx_Oracle==5.3
[...]
Successfully installed cx-Oracle-5.3
(env) $ python example.py
Example data prepped.
Gathering statistics...
Retrieving data using IN queries...
Retrieving 1 rows: 0.0738840103149 s (13.5347282279 rows/s)
Retrieving 5 rows: 0.340064048767 s (14.7031125993 rows/s)
Retrieving 10 rows: 0.670958995819 s (14.9040404292 rows/s)
Retrieving 25 rows: 1.6641638279 s (15.0225594265 rows/s)
Retrieving 50 rows: 3.36831688881 s (14.8442090369 rows/s)
Retrieving 100 rows: 6.71426200867 s (14.8936696052 rows/s)
```

My expectation was that performance would not be significantly impaired by upgrading the oracle bindings.

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?

64-Bit Python compiled on Ubuntu Xenial 16.04.

2. What is your version of cx_Oracle?

See above, I tested 5.2, 5.3 and 6.0rc2 with newer versions being affected.

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?

I am using oracle-instantclient11.2-basic release 11.2.0.3.0-1, converted from the official RPMs using alien.

```
(env) $ dpkg -L oracle-instantclient11.2-basic
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/oracle-instantclient11.2-basic
/usr/share/doc/oracle-instantclient11.2-basic/changelog.Debian.gz
/usr/share/doc/oracle-instantclient11.2-basic/copyright
/usr/lib
/usr/lib/oracle
/usr/lib/oracle/11.2
/usr/lib/oracle/11.2/client64
/usr/lib/oracle/11.2/client64/bin
/usr/lib/oracle/11.2/client64/bin/genezi
/usr/lib/oracle/11.2/client64/bin/adrci
/usr/lib/oracle/11.2/client64/lib
/usr/lib/oracle/11.2/client64/lib/ojdbc5.jar
/usr/lib/oracle/11.2/client64/lib/libnnz11.so
/usr/lib/oracle/11.2/client64/lib/xstreams.jar
/usr/lib/oracle/11.2/client64/lib/libocci.so.11.1
/usr/lib/oracle/11.2/client64/lib/libociei.so
/usr/lib/oracle/11.2/client64/lib/libocijdbc11.so
/usr/lib/oracle/11.2/client64/lib/ojdbc6.jar
/usr/lib/oracle/11.2/client64/lib/libclntsh.so.11.1
```

4. What is your version of the Oracle Database?

For testing it on a clean and minimal database, I pulled a docker container from here:

https://hub.docker.com/r/sath89/oracle-xe-11g/

I created the container with this command:

```
# docker run -d -p 8080:8080 -p 1521:1521 sath89/oracle-xe-11g
```

The only modification to the default settings I did was to enable OMF:

```
SQL> alter session set db_create_file_dest='/u01/app/oracle';
```

5. What is your OS and version?

Ubuntu Linux 16.04.2 Xenial Xerus. But the same problem has shown up on customer systems running Red Hat
Enterprise Linux 6 as well as SuSE Enterprise Linux 11.

6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.

```
torsten.landschoff@horatio:~/cxora-performance$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

RHEL6 and SLES11 use different compiler versions though.

7. What environment variables did you set?  How *exactly* did you set them?

Apart from locale and LD_LIBRARY_PATH for the Oracle libs, none of the ca. 100 environment variables set
in my session should be relevant here.

```
$ env|grep ^LC_
LC_PAPER=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_MONETARY=de_DE.UTF-8
LC_NUMERIC=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
$ env|grep ^LANG
LANG=en_US.UTF-8
LANGUAGE=en_US
```

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?

See above for the commands. I was logged in as my LDAP user `torsten.landschoff` without any special
privileges.

9. What error(s) you are seeing?

I did not get any errors just slow execution. Interestingly though the client seems to be idling while
the oracle process on the database side is running at 100% CPU.

**Comment by Bluehorn** [comment] 2017-07-28 14:24
Great, I meant to file this from my company account @tlandschoff-scale.

One thing I would like to add: This seems to happen only on string columns. Doing an `in` query on the id column is as fast as I could wish.

**Comment by anthony-tuininga** [comment] 2017-07-28 16:54
Ok. I figured out what is going on here! This is a sqlalchemy issue mixed in with an optimiser weakness. Specifically, sqlalchemy is converting all Python strings to Python unicode values. cx_Oracle in Python 2.x treats all unicode bind values as NVARCHAR2. And the optimiser says that it can't use the index because the index is on VARCHAR2 but the bind value is NVARCHAR2! If you try this code directly in cx_Oracle using regular strings the problem doesn't occur. If you try this using Python 3 instead (with sqlalchemy) the problem also does not occur.

As to why 5.2 "works" and 5.3 and higher do not -- that is because sqlalchemy is looking for the presence of "cx_Oracle.UNICODE" -- which was dropped in 5.3. This was not needed since cx_Oracle has supported unicode values for some time already. The reason Python 2.x treats unicode values as NVARCHAR2 is historical and based on a misunderstanding of how Oracle treats VARCHAR2 and NVARCHAR2 -- but it won't be changed now. This needs to be addressed in sqlalchemy. And if you can upgrade to Python 3 you can also avoid this issue. Hope that explains things!

I'm not familiar enough with the internals of sqlalchemy to be able to suggest a patch. The internal flag _cx_oracle_with_unicode=False in 5.2 and is True in 5.3 and up -- but not sure what that is doing exactly! I am more than willing to answer any questions that they might have, so if you log an issue with them, please let me know!

**Closed** 2017-07-28 16:56 UTC
Labels: question

**Comment by anthony-tuininga** [comment] 2017-07-28 17:23
Ok. I created an issue instead: https://bitbucket.org/zzzeek/sqlalchemy/issues/4035.

**Comment by zzzeek** [comment] 2017-07-28 18:52
OK that analysis is helpful, because this came up as sudden failure for us in 5.3 that we had to rush to fix (and apparently i didn't fix it correctly), see https://bitbucket.org/zzzeek/sqlalchemy/issues/4035/ for further detail

**Comment by zzzeek** [comment] 2017-07-28 19:37
@Bluehorn would you be able to run this patch against cx_Oracle 5.3 / 6.0beta and ensure it fixes your issue?  I have this up in gerrit to revert issue 3937 basically, but since you have a suite ready to go this would let me release today:

```
diff --git a/lib/sqlalchemy/dialects/oracle/cx_oracle.py b/lib/sqlalchemy/dialects/oracle/cx_oracle.py
index f6c3c97..aae3b96 100644
--- a/lib/sqlalchemy/dialects/oracle/cx_oracle.py
+++ b/lib/sqlalchemy/dialects/oracle/cx_oracle.py
@@ -723,7 +723,8 @@ class OracleDialect_cx_oracle(OracleDialect):
             self._cx_oracle_string_types = set()
             self._cx_oracle_with_unicode = False
         elif util.py3k or (
-                self.cx_oracle_ver >= (5,) and not \
+                self.cx_oracle_ver >= (5,) and
+                self.cx_oracle_ver < (5, 3) and not \
                 hasattr(self.dbapi, 'UNICODE')
         ):
             # cx_Oracle WITH_UNICODE mode.  *only* python

```

**Comment by anthony-tuininga** [comment] 2017-07-28 19:57
As noted in the Bitbucket issue, the only version that supported UNICODE mode was 5.0. I can confirm, however, that the supplied patch corrects the issue.

**Comment by Bluehorn** [comment] 2017-07-28 20:14
Guys, you are incredible! Let me see if this makes the difference.

**Comment by Bluehorn** [comment] 2017-07-28 20:24
I just checked and it looks good!

```
$ pip install cx_Oracle==6.0rc2
[...]
$ python example.py 
Example data prepped.
Gathering statistics...
Retrieving data using IN queries...
Retrieving 1 rows: 0.00219702720642 s (455.160499186 rows/s)
Retrieving 5 rows: 0.00181484222412 s (2755.0604309 rows/s)
Retrieving 10 rows: 0.00184082984924 s (5432.3325994 rows/s)
Retrieving 25 rows: 0.00284099578857 s (8799.73145351 rows/s)
Retrieving 50 rows: 0.00473380088806 s (10562.3369428 rows/s)
Retrieving 100 rows: 0.00738000869751 s (13550.1195322 rows/s)
$ pip install cx_Oracle==5.3
[...]
Successfully installed cx-Oracle-5.3
$ python example.py 
Example data prepped.
Gathering statistics...
Retrieving data using IN queries...
Retrieving 1 rows: 0.00319004058838 s (313.475635277 rows/s)
Retrieving 5 rows: 0.00228691101074 s (2186.35529608 rows/s)
Retrieving 10 rows: 0.00221109390259 s (4522.64826396 rows/s)
Retrieving 25 rows: 0.00298190116882 s (8383.91300872 rows/s)
Retrieving 50 rows: 0.00449299812317 s (11128.4266384 rows/s)
Retrieving 100 rows: 0.00710892677307 s (14066.8209411 rows/s)
```

Thanks, especially for the analysis of this problem. @anthony-tuininga How did you find out? I looked into this and was totally at loss at what was causing this.

**Comment by anthony-tuininga** [comment] 2017-07-28 20:31
@Bluehorn, this isn't the first time I've seen this sort of problem. :-) So when you said the database server was busy, I examined the statements that were being executed and then the types of the bind variables that were being used. From there it was fairly straightforward to verify that this was an VARCHAR2/NVARCHAR2 issue. Rewriting the test case for cx_Oracle directly (without SQLAlchemy getting in the way) was also a help in tracking this down. After that, it was a matter of looking at the SQLAlchemy code to see if I could figure out why it was doing what it was doing. Then @zzzeek could take it from there. :-)

**Comment by Bluehorn** [comment] 2017-07-31 09:26
Just in case somebody else runs into this ticket searching for a solution: This has been corrected in [SQLAlchemy 1.1.2](http://www.sqlalchemy.org/blog/2017/07/24/sqlalchemy-1.1.12-released/). Thanks a bunch!

SQLAlchemy 1.2.0b2 and 1.0.18 have been corrected as well.

**Comment by zzzeek** [comment] 2017-07-31 12:28
the fix is unreleased still, and apparently the doc build on the site failed to show the upcoming changes, this will be in 1.2.0b3, 1.1.13, 1.0.19

**Comment by tlandschoff-scale** [comment] 2017-08-14 07:57
For reference, SQLAlchemy 1.1.13 and 1.0.19 were released:

http://docs.sqlalchemy.org/en/latest/changelog/changelog_11.html#change-1.1.13
http://docs.sqlalchemy.org/en/latest/changelog/changelog_10.html#change-1.0.19

Both include the fix for this issue.
