### ISSUE TITLE
ORA-03113 with SET PLSCOPE_SETTINGS

### ISSUE THREAD

**Issue by jkvetina** [oracle/python-cx_Oracle#267] opened 2019-02-12 21:57 UTC
```python
import cx_Oracle

tns = {
  'user'    : '***',
  'pwd'     : '***',
  'host'    : '127.0.0.1',
  'port'    : 1521,
  'service' : 'orcl',
}
dsn = cx_Oracle.makedsn(tns['host'], tns['port'], service_name = tns['service'])

conn = cx_Oracle.connect(tns['user'], tns['pwd'], dsn)
conn.cursor().execute("ALTER SESSION SET PLSCOPE_SETTINGS='IDENTIFIERS:NONE'")

conn.cursor().execute("ALTER PACKAGE err COMPILE")  # try to recompile any package
print('OK\n')
```
This works OK as expected, BUT it fails when you switch PLSCOPE_SETTINGS to:
```python
conn.cursor().execute("ALTER SESSION SET PLSCOPE_SETTINGS='IDENTIFIERS:ALL, STATEMENTS:ALL'")
```

> Traceback (most recent call last):
>   File "***.py", line 15, in <module>
>     conn.cursor().execute("ALTER PACKAGE err COMPILE")  # try to recompile any package
> cx_Oracle.OperationalError: ORA-03113: end-of-file on communication channel
> Process ID: 11454
> Session ID: 293 Serial number: 53654
 

I used ALTER SYSTEM and run just recompilation from Python, but it also fails.
Content of the package/procedure doesnt matter.

**Same script run OK in SQL Developer 18:**
```sql
ALTER SESSION SET PLSCOPE_SETTINGS='IDENTIFIERS:ALL, STATEMENTS:ALL';
ALTER PACKAGE err COMPILE;
```

I need this to run utPLSQL tests from Python.
cx_Oracle 7.0.0, Python 3.6.4 on Mac OS 10.14.2, client 11.2, Oracle 18.3 in Virtualbox

**Comment by cjbj** [comment] 2019-02-12 22:22
The first thing to try is to use a more recent version of the client - try 12.2. 
 The second is to try the same commands with SQL*Plus
After that, some trace files would be useful.

**Comment by jkvetina** [comment] 2019-02-13 09:33
```python
print(cx_Oracle.clientversion(), cx_Oracle.version)
(12, 2, 0, 1, 0) 7.1.0
```

Thanks for the reply, I installed latest client and uninstalled and reinstalled cx_Oracle, rebooted.
Still get this error:
```
cx_Oracle.OperationalError: ORA-03113: end-of-file on communication channel
```

But I tried also SQLplus and got this error too, so it is not cx related I guess.
```
SQL> ALTER SESSION SET PLSCOPE_SETTINGS='IDENTIFIERS:ALL, STATEMENTS:ALL';

Session altered.

SQL> 
SQL> ALTER PACKAGE err COMPILE;
ERROR:
ORA-03113: end-of-file on communication channel
Process ID: 11314
Session ID: 286 Serial number: 140728898453830
```

So you want Oracle trace?

**Comment by cjbj** [comment] 2019-02-13 09:50
If it reproduces with SQL*Plus, the problem is out of scope for this cx_Oracle repo.

I did a quick test on macOS with your statements and didn't see any error:
```
SQL*Plus: Release 12.2.0.1.0 Production on Wed Feb 13 20:47:16 2019

Copyright (c) 1982, 2017, Oracle.  All rights reserved.

Last Successful login time: Wed Feb 13 2019 11:13:26 +11:00

Connected to:
Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 - Production

SQL> ALTER SESSION SET PLSCOPE_SETTINGS='IDENTIFIERS:NONE';

Session altered.

SQL> ALTER PACKAGE beachpkg COMPILE;

Package altered.

SQL> ALTER SESSION SET PLSCOPE_SETTINGS='IDENTIFIERS:ALL, STATEMENTS:ALL';

Session altered.
```

**Comment by jkvetina** [comment] 2019-02-13 10:01
Setting identifier to ALL runs ok, but try to recompile anything after that.

**Comment by jkvetina** [comment] 2019-02-13 10:08
I found another soul with similar issue from 2013, so I am screwed, 6 years later still not fixed.
https://www.orafaq.com/forum/t/185761/

You can close this, sorry, it is not cx related. Thanks.

**Comment by anthony-tuininga** [comment] 2019-02-13 15:32
I'm sorry we couldn't be of help in this case. Sounds like there's a workaround anyway!

**Closed by anthony-tuininga** 2019-02-13 15:32 UTC
Labels: question

**Comment by cjbj** [comment] 2019-02-13 21:45
Recompiling works:
```
SQL*Plus: Release 12.2.0.1.0 Production on Thu Feb 14 08:41:01 2019

Copyright (c) 1982, 2017, Oracle.  All rights reserved.

Last Successful login time: Wed Feb 13 2019 20:46:40 +11:00

Connected to:
Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 - Production

SQL> ALTER SESSION SET PLSCOPE_SETTINGS='IDENTIFIERS:NONE';

Session altered.

SQL> ALTER PACKAGE beachpkg COMPILE;

Package altered.

SQL> ALTER SESSION SET PLSCOPE_SETTINGS='IDENTIFIERS:ALL, STATEMENTS:ALL';

Session altered.

SQL> ALTER PACKAGE beachpkg COMPILE;

Package altered.

SQL> 
```

The URL you gave doesn't immediately seem to match your errors, but maybe you know more.  I suggest you (i) do a quick check on Linux or Windows with a sqlplus 18.3, (ii) jump on [OTN](https://community.oracle.com/community/groundbreakers/database/developer-tools/sql_and_pl_sql) and ask there.

**Comment by jkvetina** [comment] 2019-02-13 21:59
Thanks, I will run it manually from SQL Developer, I cant get it work anywhere else.
